---
output:
  html_document:
    toc: true
    toc_depth: 3
---

<div class="container">
<div class="jumbotron" style="margin-left:-15px">
<h1 class="title">Automated Collection of Web and Social Data</h1>
<h2 class="subtitle">ECPR Summer School in Methods and Techniques</h2>
<p>Central European University, Budapest, July 30-August 3 2018</p>
</div>
</div>

An increasingly vast wealth of data is freely available on the web -- from election results and legislative speeches to social media posts, newspaper articles, and press releases, among many other examples. Although this data is easily accessible, in most cases it is available in an unstructured format, which makes its analysis challenging. The goal of this course is to gain the skills necessary to automate the process of downloading, cleaning, and reshaping web and social data using the R programming language for statistical computing. We will cover all the most common scenarios: scraping data available in multiple pages or behind web forms, interacting with APIs and RSS feeds such as those provided by most media outlets, collecting data from Facebook and Twitter, extracting text and table data from PDF files, and manipulating datasets into a format ready for analysis.

We will follow a "learning-by-doing" approach, with short guided coding sessions followed by data challenges that will prompt participants to practice what they just learned.

# Instructor

<table class = "table table-striped">
<tr>
<td><a href="http://www.pablobarbera.com"><strong>Pablo Barberá</strong></a></td>
<td><a href="mailto:P.Barbera@lse.ac.uk">P.Barbera@lse.ac.uk</a></td>
<td><a href="https://www.twitter.com/p_barbera">@p_barbera</a></td>
</tr>
</table>


# Schedule

<table class = "table table-striped table-hover">
<tr>
<td>Monday July 30, 2018</td>
<td><b>Session 1</b></td>
<td>Basics of webscraping. Scraping web data in table format.</td>
<td> 14:00&ndash;15:30 </td>
</tr>

<tr>
<td></td>
<td><b>Session 2</b></td>
<td>Scraping web data in unstructured format.</td>
<td> 16:00&ndash;17:30 </td>
</tr>

<td>Tuesday July 31, 2018</td>
<td><b>Session 1</b></td>
<td>Scraping data behind web forms with Selenium.</td>
<td> 14:00&ndash;15:30 </td>
</tr>

<tr>
<td></td>
<td><b>Session 2</b></td>
<td>Extracting media text from newspaper articles using RSS feeds.</td>
<td> 16:00&ndash;17:30 </td>
</tr>


<td>Wednesday August 1st, 2018</td>
<td><b>Session 1</b></td>
<td>Interacting with web APIs</td>
<td> 14:00&ndash;15:30 </td>
</tr>

<tr>
<td></td>
<td><b>Session 2</b></td>
<td>Regular expressions. Basics of text analysis.</td>
<td> 16:00&ndash;17:30 </td>
</tr>

<td>Thursday August 2nd, 2018</td>
<td><b>Session 1</b></td>
<td>Collecting data from Twitter's Streaming API</td>
<td> 14:00&ndash;15:30 </td>
</tr>

<tr>
<td></td>
<td><b>Session 2</b></td>
<td>Collecting data from Twitter's REST API.</td>
<td> 16:00&ndash;17:30 </td>
</tr>

<td>Friday August 3rd, 2018</td>
<td><b>Session 1</b></td>
<td>Extracting data from PDF files</td>
<td> 14:00&ndash;15:30 </td>
</tr>

<tr>
<td></td>
<td><b>Session 2</b></td>
<td>Dealing with encoding issues. Exception handling.</td>
<td> 16:00&ndash;17:30 </td>
</tr>

</table>


# Prerequisites

The course will assume intermediate familiarity with the R statistical programming language. Participants should be able to know how to read datasets in R, work with vectors and data frames, and run basic statistical analyses, such as linear regression. More advanced knowledge of statistical computing, such as writing functions and loops, is helpful but not required.

Students are expected to bring a laptop to class and follow along the coding section of each session.

# Software 

This course will use [R](https://www.r-project.org/), which is a free and open-source programming language primarily used for statistics and data analysis. We will also use [RStudio](https://www.rstudio.com/), which is an easy-to-use interface to R. 

Installing R or RStudio prior to the workshop is not necessary. The instructor will provide individual login details to an RStudio Server that all workshop participants can access to run their code.

# License and credit

Science should be open, and this course builds up other open licensed material, so unless otherwise noted, all materials for this class are licensed under a <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

The layout for this website was designed by [Jeffrey Arnold](http://www.jrnold.me/) (thanks!).

The source for the materials of this course is on GitHub at <a href="https://github.com/pablobarbera/ECPR-SC104">pablobarbera/ECPR-SC104</a>

# Feedback

If you have any feedback on the course or find any typos or errors in this website go to [issues](https://github.com/pablobarbera/ECPR-SC104/issues), click on the "New Issue" button to create a new issue, and add your suggestion or describe the problem.


