---
title: Readings
---

<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">

<h2 id="key" class="panel-title">
<a data-toggle="collapse" href="#collapse1">Recommended readings</a>
</h2>
</div>
<div id="collapse1" class="panel-collapse collapse in" style="margin:12px">

<ul>
<li><p>Klašnja, M., Barberá, P., Beauchamp, N., Nagler, J., & Tucker, J. (2016). <a href="http://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780190213299.001.0001/oxfordhb-9780190213299-e-3">Measuring public opinion with social media data</a>. In <i>The Oxford Handbook of Polling and Survey Methods.</i></p></li>

<li><p>Golder, S. A., & Macy, M. W. (2014). <a href="http://www.annualreviews.org/doi/full/10.1146/annurev-soc-071913-043145">Digital footprints: Opportunities and challenges for online social research.</a> <i>Annual Review of Sociology</i>, 40(1), 129.</p>
</li>

<li><p>Lazer, D. & and Radford, J. (2017). <a href="http://www.annualreviews.org/doi/abs/10.1146/annurev-soc-060116-053457">Data ex Machina: Introduction to Big Data.</a> <i>Annual Review of Sociology</i>.</p>
</li>

<li><p>Matloff, N. (2011). <i>The art of R programming: A tour of statistical software design.</i> No Starch Press.</p></li>

<li><p>Munzert, S., Rubba, C., Meißner, P., & Nyhuis, D. (2014). <i>Automated data collection with R: A practical guide to web scraping and text mining.</i> John Wiley & Sons.</p></li>

<li><p>Ravindran, S. K., & Garg, V. (2015). <i>Mastering social media mining with R.</i> Packt Publishing Ltd.</p></li>

<li><p>Ruths, D., & Pfeffer, J. (2014). <a href="http://science.sciencemag.org/content/346/6213/1063.full">Social media for large studies of behavior</a>. <i>Science</i>, 346(6213), 1063-1064.</p></li>

<li><p>Salganik, M. (2017). <a href="http://www.bitbybitbook.com/">Bit by Bit: Social Research in the Digital Age.</a> Princeton, NJ: Princeton University Press. Open review edition.</p>
</li>

<li><p>Steinert-Threlkeld, Z. (2017, forthcoming) <a href="https://www.cambridge.org/core/elements/twitter-as-data/27B3DE20C22E12E162BFB173C5EB2592">Twitter as Data</a>. Cambridge University Press.<p></li>

<li><p>Theocharis, Y., Barberá, P., Fazekas, Z., Popa, S. A. and Parnet, O. (2016), <a href="http://onlinelibrary.wiley.com/doi/10.1111/jcom.12259/abstract">A Bad Workman Blames His Tweets: The Consequences of Citizens' Uncivil Twitter Use When Interacting With Party Candidates</a>. <i>Journal of Communication</i>, 66: 1007–1031.</p>
</li>

<li><p>Tucker, J. A., Theocharis, Y., Roberts, M. E., & Barberá, P. (2017). <a href="https://www.journalofdemocracy.org/sites/default/files/Tucker-28-4.pdf">From Liberation to Turmoil: Social Media And Democracy</a>. <i>Journal of Democracy</i>, 28(4), 46-59.</p></li>
</ul>
</div>
</div>
</div>

